server:
  port: 7017

spring:

  data:
    mongodb:
      host: 121.36.32.53
      port: 27017
      database: mongo_demo
      username: mongo_demo
      password: { MONGO_DEMO_PASSWORD }

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  output:
    ansi:
      enabled: always

knife4j:
  enable: true

logging:
  level:
    ROOT: warn
    com.github.wanggaolei2019: info
    org.mongodb.driver.protocol.command: debug
